#!/bin/bash

# ----------------------------------------------------------------------------------
# ------------------------ PUT YOUR RUNNING COMMAND(s) HERE ------------------------
# ----------------------------------------------------------------------------------
# ----- This sctipt is executed inside our GPU environment:
# -----     * all output files generated by `build.sh` are placed in this script's workdir
# -----     * feel free to execute `ls` form here to check the content of the workdir
# ----------------------------------------------------------------------------------

# Cache the dataset.
FILE_PATH="/tmp/dreamteam.dataset"
FILE_URL="https://www.kaggle.com/api/v1/datasets/download/<USERNAME>/<DATASET_NAME>"

if [ ! -f "$FILE_PATH" ]; then
    echo "File does not exist. Downloading..."
    wget --no-verbose -O ${FILE_PATH} ${FILE_URL}
    if [ $? -eq 0 ]; then
        echo "Download completed successfully."
    else
        echo "Download failed."
        exit 1
    fi
else
    echo "File already exists. Skipping download."
fi

# Do something with the dataset.
ls -lh ${FILE_PATH}
